version: "3.9"
services:
  homepage:
      image: ghcr.io/gethomepage/homepage:latest
      container_name: homepage
      environment:
        - HOMEPAGE_VAR_TITLE=${HOMEPAGE_VAR_TITLE}
        - HOMEPAGE_VAR_SEARCH_PROVIDER=${HOMEPAGE_VAR_SEARCH_PROVIDER}
        - HOMEPAGE_VAR_HEADER_STYLE=${HOMEPAGE_VAR_HEADER_STYLE}
        - HOMEPAGE_VAR_WEATHER_CITY=${HOMEPAGE_VAR_WEATHER_CITY}
        - HOMEPAGE_VAR_WEATHER_LAT=${HOMEPAGE_VAR_WEATHER_LAT}
        - HOMEPAGE_VAR_WEATHER_LONG=${HOMEPAGE_VAR_WEATHER_LONG}
        - HOMEPAGE_VAR_WEATHER_TIME=${TIMEZONE}
        - HOMEPAGE_VAR_WEATHER_UNIT=${HOMEPAGE_VAR_WEATHER_UNIT}
      volumes:
        - ${DATA_ROOT}/homepage/config:/app/config
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ${DATA_ROOT}/homepage/data:/data
      restart: unless-stopped
      ports:
        - 3000:3000
